spring.application.name=PM-Config-Server

# Management Endpoints
management.info.env.enabled=true
management.endpoints.web.exposure.include=info,health

# Application Info
info.app.name=${spring.application.name}
info.app.description=Patient Management System
info.app.version=1.0.0
info.app.status=UP
