spring.application.name=PM-Config-Server
server.port=8888

# Eureka Instance Configuration
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.lease-expiration-duration-in-seconds=10
eureka.instance.lease-renewal-interval-in-seconds=5

# Eureka Client Configuration
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.eureka-server-connect-timeout-seconds=5
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Eureka Server Configuration
eureka.server.eviction-interval-timer-in-ms=5000

# Management Endpoints
management.info.env.enabled=true
management.endpoints.web.exposure.include=info,health

# Application Info
info.app.name=${spring.application.name}
info.app.description=Patient Management System
info.app.version=1.0.0
info.app.status=UP


# 1. The Root Repository URL (Must end in .git)
spring.cloud.config.server.git.uri=https://github.com/shubham1617/Hospital-Management-System.git

# 2. The Branch Name (Use 'development' since that is your branch)
spring.cloud.config.server.git.default-label=development
spring.cloud.config.server.git.clone-on-start=true

# 3. The Path inside the repo where the properties files live
# Do NOT include the full URL here, just the folder path from the root
spring.cloud.config.server.git.search-paths=PM-Common-Config/common,PM-Common-Config/{application}
#PM-Config-Server/doctor-service,PM-Config-Server/appointment-service